#config/sidekiq_schedule.yml

HardWorker:
  cron: "*/5 * * * *"
  class: "HardWorker"
  queue: default
ChatActionTimingCheckWorker:
  cron: "* * * * *" # 每分钟运行一次
  class: 'ChatActionTimingCheckWorker'
  queue: default